# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: gymtter
email: honeniq@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  gymtterは、ジムに行ったことを報告すると「えらい」と誉めてくれるTwitter上のbotです。
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://gymtter.honeniq.net" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: gymtter

# Build settings
markdown: kramdown
kramdown:
  input: GFM
theme: jekyll-theme-leap-day
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jemoji
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Cayman Setings
show_downloads: false
google_analytics: UA-6905078-5
github:
  - is_project_page: false
